# Generated by Django 3.2.5 on 2021-08-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
