# Generated by Django 3.2.5 on 2021-07-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.country'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(to='restaurants.Dish'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.city'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='employers',
            field=models.ManyToManyField(to='restaurants.Employee'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menus',
            field=models.ManyToManyField(to='restaurants.Menu'),
        ),
    ]
