# Generated by Django 3.2.5 on 2021-08-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_auto_20210802_1117'),
        ('cars', '0002_auto_20210802_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='car',
            name='population_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(
                choices=[('small', 'Small'), ('midsize', 'Midsize'), ('large', 'Large'), ('luxury', 'Luxury'),
                         ('sports', 'Sports')], default='midsize', max_length=20),
        ),
    ]
