# Generated by Django 3.2.5 on 2021-08-02 14:26

from django.db import migrations, models


def copy_fuel_types_from_cars(apps, schema_editor):
    Cars = apps.get_model("cars", "Car")
    FuelTypes = apps.get_model("cars", "FuelType")
    for car in Cars.objects.all():
        FuelTypes.objects.get_or_create(fuel_type=car.fuel_type)


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210802_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('gas', 'Gas'), ('electric', 'Electric')], default='petrol', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
            },
        ),
        migrations.RunPython(copy_fuel_types_from_cars),
    ]
