# Generated by Django 3.2.5 on 2021-08-02 16:27

from django.db import migrations, models
import django.db.models.deletion


def fill_fk_to_fuel_types(apps, schema_editor):
    Cars = apps.get_model("cars", "Car")
    FuelTypes = apps.get_model("cars", "FuelType")
    for car in Cars.objects.all():
        car.fuel = FuelTypes.objects.get(fuel_type=car.fuel_type)
        car.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_fueltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.fueltype'),
            preserve_default=False,
        ),
        migrations.RunPython(fill_fk_to_fuel_types),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
    ]
