# Generated by Django 3.2.5 on 2021-08-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210802_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='population_type',
        ),
        migrations.AddField(
            model_name='car',
            name='pollutant_type',
            field=models.CharField(choices=[('a+', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.brand'),
        ),
    ]
